# Use official Node.js 20 image as base
FROM node:20.16.3-slim

# Set working directory
WORKDIR /workspace

# Install global tools you want (optional)
# RUN npm install -g yarn

# Set default shell
SHELL ["/bin/bash", "-c"]
